apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins  # Pastikan label ini cocok dengan label yang ada di deployment Jenkins
  ports:
    - port: 8080          # Port untuk akses ke Jenkins UI
      targetPort: 8080     # Port di container Jenkins
      protocol: TCP
  type: NodePort          # Pilih NodePort untuk akses eksternal (bisa diganti menjadi LoadBalancer jika mendukung)
